
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=qwerty
    volumes:
      - ./configs:/configs
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database",  "postgres://postgres:qwerty@db:5432/postgres?sslmode=disable", "up", "1"]
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    links:
      - db
networks:
  new:
