
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=qwerty
    volumes:
      - ./configs:/configs
    depends_on:
      db:
        condition: service_healthy

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database",  "postgres://postgres:qwerty@db:5432/postgres?sslmode=disable", "up", "1"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    links:
      - db
networks:
  new:
